"use strict";
exports.__esModule = true;
exports.ComponentName = void 0;
exports.ComponentName = {
    BAGTAG_PRINTER: "BAGTAG_PRINTER",
    BAGTAG_FEEDER: "BAGTAG_FEEDER",
    BAGTAG_DISPENSER: "BAGTAG_DISPENSER",
    BOARDINGPASS_PRINTER: "BOARDINGPASS_PRINTER",
    BOARDINGPASS_DISPENSER: "BOARDINGPASS_DISPENSER",
    PASSPORT_READER: "PASSPORT_READER",
    BARCODE_READER: "BARCODE_READER",
    GENERAL_PURPOSE_PRINTER: "GENERAL_PURPOSE_PRINTER",
    GENERAL_PURPOSE_FEEDER: "PASSPORT_READER",
    GENERAL_PURPOSE_DISPENSER: "GENERAL_PURPOSE_DISPENSER",
    ILIMINATION: "ILIMINATION",
    ADA_PAD: "ADA_PAD",
    ANNOUNCEMENT: "ANNOUNCEMENT",
    DISPLAY: "DISPLAY",
    PAYMENT: "PAYMENT",
    CONVEYOR: "CONVEYOR",
    BIOMETRIC: "BIOMETRIC"
};
