"use strict";
/**
 * Common Use Self Service V2 API Definition
 * <h3>Definiton of the new CUSS2 API.</h3>This API definition idescribes IATA Common Use Self Service (IATA RP 1706c), a standard that allows multiple airlines to share physical kiosks or other hardware devices to offer self-services to their passengers. These services include, but are not limited to passenger check-in functionality and self-service baggage drop off. The standard also defines how airlines and other application suppliers can develop CUSS-compliant applications that are able to run on any device whose platform is CUSS-compliant.<br><br>The API definiton is accompanied by the CUSS Specification (CUSS-TS), describing in human readable form (textual and graphical) the concepts, requirements, interaction, workflows and behavior for both CUSS platforms and CUSS applications, and the CUSS Implementation Guide (CUSS-IG) describing best practices and giving examples on how to implement CUSS compliant platforms- and applications.<br><br>The API requires and includes further schema definitions/domains as<br><br>- CUSS2 Basic Schemas<br>- CUSS2 Self Bag Drop<br>- CUSS2 Biometrics<br>- CUSS2 Payments<br>- CUSS2 Illumination<br><br>The IATA Common Use Group (CUG) and the CUSS Technical Solution Group (CUSS-TSG) maintain this API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataTypes = void 0;
exports.DataTypes = {
    FOIDISO: 'DS_TYPES_FOID_ISO',
    DISCRETIONARYISO: 'DS_TYPES_DISCRETIONARY_ISO',
    FOIDJIS2: 'DS_TYPES_FOID_JIS2',
    DISCRETIONARYJIS2: 'DS_TYPES_DISCRETIONARY_JIS2',
    ISO: 'DS_TYPES_ISO',
    VING: 'DS_TYPES_VING',
    TESSA: 'DS_TYPES_TESSA',
    SAFLOK: 'DS_TYPES_SAFLOK',
    TIMELOX: 'DS_TYPES_TIMELOX',
    KABAILCO: 'DS_TYPES_KABA_ILCO',
    KABAILCOFOLIO: 'DS_TYPES_KABA_ILCO_FOLIO',
    IMAGEIR: 'DS_TYPES_IMAGE_IR',
    IMAGEVIS: 'DS_TYPES_IMAGE_VIS',
    IMAGEUV: 'DS_TYPES_IMAGE_UV',
    IMAGEPHOTO: 'DS_TYPES_IMAGE_PHOTO',
    IMAGECOAX: 'DS_TYPES_IMAGE_COAX',
    CODELINE: 'DS_TYPES_CODELINE',
    BARCODE: 'DS_TYPES_BARCODE',
    MIWA: 'DS_TYPES_MIWA',
    SCANPDF417: 'DS_TYPES_SCAN_PDF417',
    SCANAZTEC: 'DS_TYPES_SCAN_AZTEC',
    SCANDMATRIX: 'DS_TYPES_SCAN_DMATRIX',
    SCANQR: 'DS_TYPES_SCAN_QR',
    SCANCODE39: 'DS_TYPES_SCAN_CODE39',
    SCANCODE128: 'DS_TYPES_SCAN_CODE128',
    SCANCODE2OF5: 'DS_TYPES_SCAN_CODE2OF5',
    ISO7816: 'DS_TYPES_ISO7816',
    PRINT2SPAGE: 'DS_TYPES_PRINT_2S_PAGE',
    PRINT2SMULTI: 'DS_TYPES_PRINT_2S_MULTI',
    PRINTPDF: 'DS_TYPES_PRINT_PDF',
    MIFARE: 'DS_TYPES_MIFARE',
    SUICA: 'DS_TYPES_SUICA',
    ISO15961: 'DS_TYPES_ISO15961',
    RP1745: 'DS_TYPES_RP1745',
    WEIGHT: 'DS_TYPES_WEIGHT',
    HEAVYTAG: 'DS_TYPES_HEAVYTAG',
    SBDAEA: 'DS_TYPES_SBDAEA',
    SBDCUSS: 'DS_TYPES_SBDCUSS',
    EPASSPORTDG1: 'DS_TYPES_EPASSPORT_DG1',
    EPASSPORTDG2: 'DS_TYPES_EPASSPORT_DG2',
    EPASSPORTDG3: 'DS_TYPES_EPASSPORT_DG3',
    EPASSPORTDG4: 'DS_TYPES_EPASSPORT_DG4',
    EPASSPORTDG5: 'DS_TYPES_EPASSPORT_DG5',
    EPASSPORTDG6: 'DS_TYPES_EPASSPORT_DG6',
    EPASSPORTDG7: 'DS_TYPES_EPASSPORT_DG7',
    EPASSPORTDG8: 'DS_TYPES_EPASSPORT_DG8',
    EPASSPORTDG9: 'DS_TYPES_EPASSPORT_DG9',
    EPASSPORTDG10: 'DS_TYPES_EPASSPORT_DG10',
    EPASSPORTDG11: 'DS_TYPES_EPASSPORT_DG11',
    EPASSPORTDG12: 'DS_TYPES_EPASSPORT_DG12',
    EPASSPORTDG13: 'DS_TYPES_EPASSPORT_DG13',
    EPASSPORTDG14: 'DS_TYPES_EPASSPORT_DG14',
    EPASSPORTDG15: 'DS_TYPES_EPASSPORT_DG15',
    EPASSPORTDG16: 'DS_TYPES_EPASSPORT_DG16',
    EPASSPORTDG17: 'DS_TYPES_EPASSPORT_DG17',
    EPASSPORTDG18: 'DS_TYPES_EPASSPORT_DG18',
    EPASSPORTDG19: 'DS_TYPES_EPASSPORT_DG19',
    EPASSPORTDG20: 'DS_TYPES_EPASSPORT_DG20',
    EPAYMENT: 'DS_TYPES_EPAYMENT',
    ILLUMINATION: 'DS_TYPES_ILLUMINATION',
    SSML10: 'DS_TYPES_SSML10',
    SSML11: 'DS_TYPES_SSML11',
    KEY: 'DS_TYPES_KEY',
    KEYUP: 'DS_TYPES_KEY_UP',
    KEYDOWN: 'DS_TYPES_KEY_DOWN',
    BIOMETRIC: 'DS_TYPES_BIOMETRIC'
};
