/**
 * Interface providing means to handle real-time events for all predefined CUSS websocket responses
 */
export type ElevatedMetric = 'NONE' | 'BAGTAG_PRINTED' | 'BOARDINGPASS_PRINTED' | 'BAGTAG_LOW_PAPER' | 'BOARDINGPASS_LOW_PAPER' | 'BAGTAG_PAPER_OUT' | 'BOARDINGPASS_PAPER_OUT' | 'BAGTAG_ERROR' | 'BOARDINGPASS_ERROR' | 'BARCODE_SCAN' | 'PASSPORT_SCAN' | 'APP_INITIALIZE' | 'APP_UNAVAILABLE' | 'APP_AVAILABLE' | 'APP_ACTIVE' | 'APP_ACTIVE_ACCESSIBLE';

export const ElevatedMetric = {
	NONE: 'NONE' as ElevatedMetric,
	BAGTAG_PRINTED: 'BAGTAG_PRINTED' as ElevatedMetric,
	BOARDINGPASS_PRINTED: 'BOARDINGPASS_PRINTED' as ElevatedMetric,
	BAGTAG_LOW_PAPER: 'BAGTAG_LOW_PAPER' as ElevatedMetric,
	BOARDINGPASS_LOW_PAPER: 'BOARDINGPASS_LOW_PAPER' as ElevatedMetric,
	BAGTAG_PAPER_OUT: 'BAGTAG_PAPER_OUT' as ElevatedMetric,
	BOARDINGPASS_PAPER_OUT: 'BOARDINGPASS_PAPER_OUT' as ElevatedMetric,
	BAGTAG_ERROR: 'BAGTAG_ERROR' as ElevatedMetric,
	BOARDINGPASS_ERROR: 'BOARDINGPASS_ERROR' as ElevatedMetric,
	BARCODE_SCAN: 'BARCODE_SCAN' as ElevatedMetric,
	PASSPORT_SCAN: 'PASSPORT_SCAN' as ElevatedMetric,
	APP_INITIALIZE: 'APP_INITIALIZE' as ElevatedMetric,
	APP_UNAVAILABLE: 'APP_UNAVAILABLE' as ElevatedMetric,
	APP_AVAILABLE: 'APP_AVAILABLE' as ElevatedMetric,
	APP_ACTIVE: 'APP_ACTIVE' as ElevatedMetric,
	APP_ACTIVE_ACCESSIBLE: 'APP_ACTIVE_ACCESSIBLE' as ElevatedMetric
};
