"use strict";
/**
 * Common Use Self Service V2 API Definition
 * <h3>Definiton of the new CUSS2 API.</h3>This API definition idescribes IATA Common Use Self Service (IATA RP 1706c), a standard that allows multiple airlines to share physical kiosks or other hardware devices to offer self-services to their passengers. These services include, but are not limited to passenger check-in functionality and self-service baggage drop off. The standard also defines how airlines and other application suppliers can develop CUSS-compliant applications that are able to run on any device whose platform is CUSS-compliant.<br><br>The API definiton is accompanied by the CUSS Specification (CUSS-TS), describing in human readable form (textual and graphical) the concepts, requirements, interaction, workflows and behavior for both CUSS platforms and CUSS applications, and the CUSS Implementation Guide (CUSS-IG) describing best practices and giving examples on how to implement CUSS compliant platforms- and applications.<br><br>The API requires and includes further schema definitions/domains as<br><br>- CUSS2 Basic Schemas<br>- CUSS2 Self Bag Drop<br>- CUSS2 Biometrics<br>- CUSS2 Payments<br>- CUSS2 Illumination<br><br>The IATA Common Use Group (CUG) and the CUSS Technical Solution Group (CUSS-TSG) maintain this API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.StatusCodes = void 0;
exports.StatusCodes = {
    OK: 'OK',
    CANCELLED: 'CANCELLED',
    WRONGSTATE: 'WRONG_STATE',
    OUTOFSEQUENCE: 'OUT_OF_SEQUENCE',
    TIMEOUT: 'TIMEOUT',
    SESSIONTIMEOUT: 'SESSION_TIMEOUT',
    KILLTIMEOUT: 'KILL_TIMEOUT',
    SOFTWAREERROR: 'SOFTWARE_ERROR',
    CRITICALSOFTWAREERROR: 'CRITICAL_SOFTWARE_ERROR',
    CONFIGURATIONERROR: 'CONFIGURATION_ERROR',
    FORMATERROR: 'FORMAT_ERROR',
    LENGTHERROR: 'LENGTH_ERROR',
    DATAMISSING: 'DATA_MISSING',
    DATAPRESENT: 'DATA_PRESENT',
    CONSUMABLES: 'CONSUMABLES',
    THRESHOLDERROR: 'THRESHOLD_ERROR',
    THRESHOLDUSAGE: 'THRESHOLD_USAGE',
    HARDWAREERROR: 'HARDWARE_ERROR',
    NOTREACHABLE: 'NOT_REACHABLE',
    NOTRESPONDING: 'NOT_RESPONDING',
    MEDIAJAMMED: 'MEDIA_JAMMED',
    MEDIAMISPLACED: 'MEDIA_MISPLACED',
    MEDIAPRESENT: 'MEDIA_PRESENT',
    MEDIAABSENT: 'MEDIA_ABSENT',
    MEDIAHIGH: 'MEDIA_HIGH',
    MEDIAFULL: 'MEDIA_FULL',
    MEDIALOW: 'MEDIA_LOW',
    MEDIAEMPTY: 'MEDIA_EMPTY',
    MEDIADAMAGED: 'MEDIA_DAMAGED',
    MEDIAINCOMPLETELYINSERTED: 'MEDIA_INCOMPLETELY_INSERTED',
    BAGGAGEFULL: 'BAGGAGE_FULL',
    BAGGAGEUNDETECTED: 'BAGGAGE_UNDETECTED',
    BAGGAGEPRESENT: 'BAGGAGE_PRESENT',
    BAGGAGEABSENT: 'BAGGAGE_ABSENT',
    BAGGAGEOVERSIZED: 'BAGGAGE_OVERSIZED',
    BAGGAGETOOMANYBAGS: 'BAGGAGE_TOO_MANY_BAGS',
    BAGGAGEUNEXPECTEDBAG: 'BAGGAGE_UNEXPECTED_BAG',
    BAGGAGETOOHIGH: 'BAGGAGE_TOO_HIGH',
    BAGGAGETOOLONG: 'BAGGAGE_TOO_LONG',
    BAGGAGETOOFLAT: 'BAGGAGE_TOO_FLAT',
    BAGGAGETOOSHORT: 'BAGGAGE_TOO_SHORT',
    BAGGAGEINVALIDDATA: 'BAGGAGE_INVALID_DATA',
    BAGGAGEWEIGHTOUTOFRANGE: 'BAGGAGE_WEIGHT_OUT_OF_RANGE',
    BAGGAGEJAMMED: 'BAGGAGE_JAMMED',
    BAGGAGEEMERGENCYSTOP: 'BAGGAGE_EMERGENCY_STOP',
    BAGGAGERESTLESS: 'BAGGAGE_RESTLESS',
    BAGGAGETRANSPORTBUSY: 'BAGGAGE_TRANSPORT_BUSY',
    BAGGAGEMISTRACKED: 'BAGGAGE_MISTRACKED',
    BAGGAGEUNEXPECTEDCHANGE: 'BAGGAGE_UNEXPECTED_CHANGE',
    BAGGAGEACCEPTED: 'BAGGAGE_ACCEPTED',
    BAGGAGEDELIVERED: 'BAGGAGE_DELIVERED',
    BAGGAGEINTERFERENCEUSER: 'BAGGAGE_INTERFERENCE_USER',
    BAGGAGEINTRUSIONSAFETY: 'BAGGAGE_INTRUSION_SAFETY',
    BAGGAGENOTCONVEYABLE: 'BAGGAGE_NOT_CONVEYABLE',
    BAGGAGEIRREGULARBAG: 'BAGGAGE_IRREGULAR_BAG',
    BAGGAGEBAGWITHSTRAPS: 'BAGGAGE_BAG_WITH_STRAPS',
    BAGGAGEUPRIGHTBAG: 'BAGGAGE_UPRIGHT_BAG',
    BAGGAGEMULTIPLEBAGS: 'BAGGAGE_MULTIPLE_BAGS',
    BAGGAGESLOPEDBAG: 'BAGGAGE_SLOPED_BAG',
    BAGGAGEVOLUMENOTDETERMINABLE: 'BAGGAGE_VOLUME_NOT_DETERMINABLE',
    BAGGAGEOVERFLOWTUB: 'BAGGAGE_OVERFLOW_TUB'
};
